version: '3.8'
services:
  nestjs:
    container_name: service01-dev
    build: .
    depends_on:
      - kafka
    ports:
      - 3000:3000
    networks:
      dev-network:

  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
    networks:
      dev-network:

networks:
  dev-network:
    driver: bridge
